from typing import Protocol, Tuple, Any, List, Dict
import torch

class ModelDriver(Protocol):
    device: str
    dtype: torch.dtype
    n_layers: int

    def load(self, model_id: str, device: str, dtype: torch.dtype) -> None: ...
    def tokenize(self, text: str) -> torch.Tensor: ...
    def detok(self, ids: torch.Tensor) -> List[str]: ...
    def run_with_cache(self, ids: torch.Tensor) -> Tuple[torch.Tensor, Dict[str, torch.Tensor]]: ...
    def pick_next_token_topk(self, logits: torch.Tensor, topk: int) -> Tuple[int, List[Dict[str, float]]]: ...
    def lastpos_layer_snapshot(self, cache: Dict[str, torch.Tensor], layer: int, top_neur: int = 3) -> Dict[str, Any]: ...
    # NEW: flattened MLP activations across layers (last position)
    def pixel_map_lastpos(self, cache: Dict[str, torch.Tensor], layers: List[int] | None = None) -> List[float]: ...