apiVersion: v1
kind: ServiceAccount
metadata:
  name: head-cracker-builder
  namespace: build-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: head-cracker-builder
  namespace: head-cracker
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: head-cracker-builder
  namespace: head-cracker
subjects:
  - kind: ServiceAccount
    name: head-cracker-builder
    namespace: build-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: head-cracker-builder
