apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - head-cracker.yaml
  - builder-rbac.yaml
  - builder-cronjob.yaml

patches:
  - target:
      kind: CronJob
      name: head-cracker-builder
      namespace: build-system
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "18 3 * * *"
